Feat/shell bootloader baudrate
pollen-robotics/pyluos pull request #159
Opened 2022-08-25 16:36 UTC by Salem-Tho

2022-08-26 07:39 UTC, JeromeGalan commented on pyluos/tools/discover.py
> +            port = serial.Serial(serial_host, baudrate, timeout=0.05)
Why does 'os.getenv' has disapeared ?

2022-08-26 08:00 UTC, JeromeGalan commented on pyluos/tools/discover.py
> +            port = serial.Serial(serial_host, baudrate, timeout=0.05)
It's OK, baudrate parameter is passed in the main function with getenv.

2022-08-26 08:00 UTC, JeromeGalan approved these changes

2022-08-30 15:28 UTC, nicolas-rabault requested changes
Only one small thing.
@Salem-Tho you are officially a python dev ;)

2022-08-30 15:28 UTC, nicolas-rabault commented on pyluos/tools/bootloader.py
> +    print('\tbaudrate : ', args.baudrate)
this should be `--baudrate` to have something similar to the other ones.

2022-08-31 08:21 UTC, nicolas-rabault approved these changes
Nice

2022-08-31 08:21 UTC, merged